Name: gst-streaming-server
Provides: gst-streaming-server
Version: 1.0.0
Release: 1%{?dist}
License: LGPL-2.1+
Source: %{name}.tar.gz
URL: http://softus.org/products/beryllium
Vendor: Softus Inc. <contact@softus.org>
Packager: Softus Inc. <contact@softus.org>
Summary: GStreamer Streaming Server

%description
GStreamer Streaming Server.


Video streaming server based on GStreamer

%global debug_package %{nil}

Requires(pre): /usr/sbin/useradd, openssl
Requires(postun): /usr/sbin/userdel
BuildRequires: make, gcc-c++, libtool, systemd

%{?fedora:BuildRequires: gstreamer1-devel, gstreamer1-rtsp-server-devel, libsoup-devel, json-glib-devel, openssl-devel}
%{?fedora:Requires: gstreamer1-plugins-base, gstreamer1-plugins-good, gstreamer1-plugins-bad-free}

%{?rhel:BuildRequires: gtk-doc, gstreamer1-devel, gstreamer1-rtsp-server-devel, gettext-devel, libsoup-devel, json-glib-devel, openssl-devel}
%{?rhel:Requires: gstreamer1-plugins-base, gstreamer1-plugins-good, gstreamer1-plugins-bad-free}

%{?suse_version:BuildRequires: gstreamer-devel, gstreamer-rtsp-server-devel, libsoup-devel, json-glib-devel, libopenssl-devel}
%{?suse_version:Requires: gstreamer-plugins-base, gstreamer-plugins-good, gstreamer-plugins-bad}

%if 0%{?mageia}
BuildRequires: gettext-devel, gtk-doc
%ifarch x86_64 amd64
BuildRequires: lib64gstreamer1.0-devel, lib64openssl-devel, lib64soup-devel, lib64gstrtspserver-devel, lib64json-glib-devel, lib64gstreamer-plugins-base1.0-devel
Requires: lib64gstreamer-plugins-base1.0_0
%else
BuildRequires: libgstreamer1.0-devel,   libopenssl-devel,   libsoup-devel,   libgstrtspserver-devel,   libjson-glib-devel,   libgstreamer-plugins-base1.0-devel
Requires: libgstreamer-plugins-base1.0_0
%endif
%else
%endif

%prep
%setup -c %{name}
 
%build
./configure --prefix=%{_prefix}
make %{?_smp_mflags};

%install
make install DESTDIR="%buildroot" libdir="%{_libdir}"
install -D %{name}.conf %{buildroot}%{_sysconfdir}/%{name}.conf
install -D 99-%{name}.conf %{buildroot}%{_sysconfdir}/rsyslog.d/99-%{name}.conf
install -D %{name}.service %{buildroot}%{_unitdir}/%{name}.service
install -D %{name}.1 %{buildroot}%{_mandir}/man1/%{name}.1

%files
%defattr(-,root,root)
%config(noreplace) %{_sysconfdir}/%{name}.conf
%config(noreplace) %{_sysconfdir}/rsyslog.d/99-%{name}.conf
%{_mandir}/man1/%{name}.1.*
%{_bindir}/%{name}
%{_bindir}/gss-transcoder
%{_unitdir}/%{name}.service
%{_includedir}/gstreamer-1.0/gss/*
%{_libdir}/libgss-1.0.*
%{_libdir}/pkgconfig/%{name}-1.0.pc

%pre
/usr/sbin/groupadd -r gss || :
/usr/sbin/useradd -rmb /var/lib -s /sbin/nologin -g gss gss || :
chown gss:gss /var/lib/gss
chmod 775 /var/lib/gss
openssl genrsa -out /var/lib/gss/server.key 1024
openssl req -new -subj "/O=GStreamer Streaming Server/OU=autogenerated key" -key /var/lib/gss/server.key -x509 -days 36500 -out /var/lib/gss/server.crt

%post
systemctl enable %{name}
service %{name} start || :

%preun
service %{name} stop || :

%postun
/usr/sbin/userdel gss || :
/usr/sbin/groupdel gss || :

%changelog
* Mon Mar 12 2018 Pavel Bludov <pbludov@gmail.com>
+ Version 0.1.0
- Initial version.
